// AUTOGENERATED by gleamler_codegen
// Do not edit

/// Adds two signed 64-bit integers.
@external(erlang, "gleamler_nif_ffi", "add")
pub fn rust_add(a: Int, b: Int) -> Int

/// Greets a caller by name. The `String` argument is automatically decoded
/// from an Erlang binary or list; the return value is encoded back to a binary.
@external(erlang, "gleamler_nif_ffi", "greet")
pub fn rust_greet(name: String) -> String
