// AUTOGENERATED by gleamler_codegen
// Do not edit


pub opaque type Resource(a) {
  Resource
}

@internal
pub fn resource_dummy() -> Resource(a) {
  Resource
}

pub type Counter {
  Counter
}


/// Creates a new counter initialized to zero.
@external(erlang, "gleamler_nif_ffi", "counter_new")
pub fn rust_counter_new() -> Resource(Counter)

/// Atomically increments the counter and returns the *new* value.
/// `fetch_add` returns the previous value, hence the `+ 1`.
@external(erlang, "gleamler_nif_ffi", "counter_inc")
pub fn rust_counter_inc(counter: Resource(Counter)) -> Int

/// Returns the current value.
@external(erlang, "gleamler_nif_ffi", "counter_get")
pub fn rust_counter_get(counter: Resource(Counter)) -> Int
