use syn::{parse_file, FnArg, ItemFn, Pat, ReturnType};

#[derive(Debug)]
pub struct NifFunc {
    pub name: String,
    pub alias: Option<String>,
    pub args: Vec<(String, String)>,
    pub ret: String,
    pub arity: usize,
    pub docs: Vec<String>,
}

pub fn parse_nif_functions(source: &str) -> Vec<NifFunc> {
    let file = parse_file(source).expect("failed to parse lib.rs");
    let mut functions = Vec::new();
    for item in file.items {
        if let syn::Item::Fn(func) = item {
            if has_gleam_nif(&func.attrs) {
                if let Some(f) = parse_nif_function(func) {
                    functions.push(f);
                }
            }
        }
    }
    functions
}

fn has_gleam_nif(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| a.path().is_ident("gleam_nif"))
}

fn parse_nif_function(func: ItemFn) -> Option<NifFunc> {
    let name = func.sig.ident.to_string();
    let mut args = Vec::new();
    for (idx, arg) in func.sig.inputs.iter().enumerate() {
        if let FnArg::Typed(pat_type) = arg {
            let ty = type_to_string(&pat_type.ty);
            let norm_ty = normalize(&ty);
            if idx == 0 && (norm_ty == "Env" || norm_ty.ends_with("::Env")) {
                continue;
            }
            let name = match pat_type.pat.as_ref() {
                Pat::Ident(ident) => ident.ident.to_string(),
                _ => format!("arg{}", idx),
            };
            args.push((name, ty));
        }
    }
    let ret = match &func.sig.output {
        ReturnType::Default => "nil".to_string(),
        ReturnType::Type(_, ty) => type_to_string(ty),
    };
    let alias = func.attrs.iter()
        .filter(|a| a.path().is_ident("gleam_nif"))
        .find_map(|a| {
            if let syn::Meta::List(list) = &a.meta {
                list.parse_args_with(syn::punctuated::Punctuated::<syn::Meta, syn::Token![,]>::parse_terminated).ok()
            } else {
                None
            }
        })
        .and_then(|metas| {
            metas.iter().find_map(|meta| {
                if meta.path().is_ident("alias") {
                    meta.require_name_value().ok().and_then(|nv| {
                        if let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(s), .. }) = &nv.value {
                            Some(s.value())
                        } else {
                            None
                        }
                    })
                } else {
                    None
                }
            })
        });

    let arity = args.len();

        let docs: Vec<String> = func.attrs.iter()
        .filter_map(|a| {
            if a.path().is_ident("doc") {
                if let syn::Meta::NameValue(nv) = &a.meta {
                    if let syn::Expr::Lit(syn::ExprLit { lit: syn::Lit::Str(s), .. }) = &nv.value {
                        return Some(s.value().trim().to_string());
                    }
                }
            }
            None
        })
        .collect();

    Some(NifFunc { name, alias, args, ret, arity, docs })
}

fn type_to_string(ty: &syn::Type) -> String {
    use quote::ToTokens;
    ty.to_token_stream().to_string()
}

fn normalize(s: &str) -> String {
    s.split_whitespace().collect()
}

pub fn generate_erl(funcs: &[NifFunc]) -> String {
    let exports: Vec<_> = funcs.iter().map(|f| {
        let name = f.alias.as_ref().unwrap_or(&f.name);
        format!("{}/{}", name, f.arity)
    }).collect();
    let stubs: Vec<_> = funcs.iter().map(|f| {
        let name = f.alias.as_ref().unwrap_or(&f.name);
        let args: Vec<_> = (0..f.arity).map(|i| format!("_{}", (b'A' + i as u8) as char)).collect();
        format!("{}({}) -> exit(nif_library_not_loaded).", name, args.join(", "))
    }).collect();
    format!(
        r#"-module(gleamler_nif_ffi).
-export([{}]).
-on_load(init/0).
init() ->
    PrivDir = case code:which(?MODULE) of
        non_existing -> {{ok, Cwd}} = file:get_cwd(), filename:join(Cwd, "priv");
        BeamPath -> filename:join([filename:dirname(BeamPath), "..", "priv"])
    end,
    LibName = "gleamler",
    Path = filename:join(PrivDir, LibName),
    case erlang:load_nif(Path, 0) of
        ok -> ok;
        Error -> io:format("[Gleamler NIF] Load error: ~p~n", [Error]), Error
    end.
{}"#,
        exports.join(", "),
        stubs.join("\n")
    )
}

pub fn generate_gleam(funcs: &[NifFunc]) -> String {
    let mut has_option = false;
    let mut has_dict = false;
    
    for f in funcs {
        if f.ret.contains("Option") || f.args.iter().any(|(_, t)| t.contains("Option")) {
            has_option = true;
        }
        if f.ret.contains("HashMap") || f.args.iter().any(|(_, t)| t.contains("HashMap")) {
            has_dict = true;
        }
    }

    let mut out = String::from(
        "// AUTOGENERATED by gleamler_codegen\n// Do not edit\n\n",
    );

    if has_option {
        out.push_str("import gleam/option\n\n");
    }

    if has_dict {
        out.push_str("import gleam/dict\n\n");
    }

    for f in funcs {
        if !f.docs.is_empty() {
            out.push_str("/// ");
            out.push_str(&f.docs.join("\n/// "));
            out.push('\n');
        }
        let gleam_name = format!("rust_{}", f.alias.as_ref().unwrap_or(&f.name));
        let erl_name = f.alias.as_ref().unwrap_or(&f.name).clone();
        let args: Vec<_> = f.args.iter().map(|(n, t)| {
            format!("{}: {}", clean_name(n), rust_to_gleam(t))
        }).collect();
        let ret = rust_to_gleam(&f.ret);
        out.push_str(&format!(
            "@external(erlang, \"gleamler_nif_ffi\", \"{}\")\npub fn {}({}) -> {}\n\n",
            erl_name, gleam_name, args.join(", "), ret
        ));
    }
    out
}

fn clean_name(n: &str) -> String {
    n.trim_start_matches('_').to_string()
}

fn rust_to_gleam(rust: &str) -> String {
    let t = normalize(rust);
    if t.starts_with('&') {
        let inner = t[1..].trim();
        if inner == "str" { return "String".into(); }
        if inner == "[u8]" { return "BitArray".into(); }
        return rust_to_gleam(inner);
    }
    match t.as_str() {
        "i8"|"i16"|"i32"|"i64"|"isize"|"u8"|"u16"|"u32"|"u64"|"usize"|"i128"|"u128" => "Int".into(),
        "f32"|"f64" => "Float".into(),
        "bool" => "Bool".into(),
        "String" => "String".into(),
        "Atom" => "String".into(),
        "Binary"|"OwnedBinary"|"NewBinary" => "BitArray".into(),
        "nil"|"()" => "Nil".into(),
        _ => {
            if t.starts_with("Vec<") && t.ends_with(">") {
                let inner = &t[4..t.len()-1];
                if inner == "u8" {
                    return "BitArray".into();
                }
                format!("List({})", rust_to_gleam(inner))
            } else if t.starts_with("Option<") && t.ends_with(">") {
                let inner = &t[7..t.len()-1];
                format!("option.Option({})", rust_to_gleam(inner))
            } else if t.starts_with("Result<") && t.ends_with(">") {
                let inner = &t[7..t.len()-1];
                let parts = split_args(inner);
                if parts.len() == 2 {
                    format!("Result({}, {})", rust_to_gleam(&parts[0]), rust_to_gleam(&parts[1]))
                } else {
                    "Result(a, b)".into()
                }
            } else if t.starts_with("HashMap<") && t.ends_with(">") {
                let inner = &t[8..t.len()-1];
                let parts = split_args(inner);
                if parts.len() == 2 {
                    format!("Dict({}, {})", rust_to_gleam(&parts[0]), rust_to_gleam(&parts[1]))
                } else {
                    "Dict(k, v)".into()
                }
            } else if t.starts_with("ResourceArc<") && t.ends_with(">") {
                t[12..t.len()-1].to_string()
            } else if t.starts_with('(') && t.ends_with(')') {
                let inner = &t[1..t.len()-1];
                let parts: Vec<_> = inner.split(',').map(|s| rust_to_gleam(s.trim())).collect();
                format!("#({})", parts.join(", "))
            } else {
                t
            }
        }
    }
}

fn split_args(s: &str) -> Vec<String> {
    let mut depth = 0i32;
    let mut cur = String::new();
    let mut res = Vec::new();
    for c in s.chars() {
        match c {
            '<' | '(' => { depth += 1; cur.push(c); }
            '>' | ')' => { depth -= 1; cur.push(c); }
            ',' if depth == 0 => { res.push(cur.trim().to_string()); cur.clear(); }
            _ => cur.push(c),
        }
    }
    if !cur.is_empty() { res.push(cur.trim().to_string()); }
    res
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn parse_empty_file() {
        assert!(parse_nif_functions("// nothing here").is_empty());
    }

    #[test]
    fn parse_simple_fn() {
        let src = r#"
#[gleam_nif]
pub fn add(a: i64, b: i64) -> i64 {
    a + b
}
"#;
        let funcs = parse_nif_functions(src);
        assert_eq!(funcs.len(), 1);
        let f = &funcs[0];
        assert_eq!(f.name, "add");
        assert_eq!(f.arity, 2);
        assert_eq!(f.args, vec![("a".into(), "i64".into()), ("b".into(), "i64".into())]);
        assert_eq!(f.ret, "i64");
    }

    #[test]
    fn parse_env_skipped() {
        let src = r#"
#[gleam_nif]
pub fn foo(env: Env, x: i64, name: String) -> bool {
    true
}
"#;
        let funcs = parse_nif_functions(src);
        assert_eq!(funcs[0].arity, 2);
        assert_eq!(funcs[0].args[0].0, "x");
        assert_eq!(funcs[0].args[1].0, "name");
    }

    #[test]
    fn parse_dirty_attributes() {
        let src = r#"
#[gleam_nif(dirty_cpu)]
pub fn heavy(n: i64) -> i64 { n }
"#;
        let funcs = parse_nif_functions(src);
        assert_eq!(funcs[0].name, "heavy");
    }

    #[test]
    fn erl_output_smoke() {
        let funcs = vec![NifFunc {
            name: "add".into(),
            args: vec![("a".into(), "i64".into()), ("b".into(), "i64".into())],
            ret: "i64".into(),
            arity: 2,
        }];
        let out = generate_erl(&funcs);
        assert!(out.contains("-export([add/2])."));
        assert!(out.contains("add(_A, _B) -> exit(nif_library_not_loaded)."));
        assert!(out.contains("-module(gleamler_nif_ffi)."));
    }

    #[test]
    fn gleam_output_basic() {
        let funcs = vec![NifFunc {
            name: "greet".into(),
            args: vec![("name".into(), "String".into())],
            ret: "String".into(),
            arity: 1,
        }];
        let out = generate_gleam(&funcs);
        assert!(out.contains(r#"@external(erlang, "gleamler_nif_ffi", "greet")"#));
        assert!(out.contains("pub fn rust_greet(name: String) -> String"));
    }

    #[test]
    fn gleam_output_complex_types() {
        let funcs = vec![NifFunc {
            name: "calc".into(),
            args: vec![
                ("items".into(), "Vec<i64>".into()),
                ("flag".into(), "Option<bool>".into()),
            ],
            ret: "Result<String, i64>".into(),
            arity: 2,
        }];
        let out = generate_gleam(&funcs);
        assert!(out.contains("import gleam/option"));
        assert!(out.contains("items: List(Int)"));
        assert!(out.contains("flag: option.Option(Bool)"));
        assert!(out.contains("Result(String, Int)"));
    }

    #[test]
    fn gleam_tuple_type() {
        let funcs = vec![NifFunc {
            name: "pair".into(),
            args: vec![("a".into(), "i64".into()), ("b".into(), "String".into())],
            ret: "(i64, String)".into(),
            arity: 2,
        }];
        let out = generate_gleam(&funcs);
        assert!(out.contains("#(Int, String)"));
    }

    #[test]
    fn gleam_dict_type() {
        let funcs = vec![NifFunc {
            name: "m".into(),
            args: vec![("x".into(), "HashMap<String, i64>".into())],
            ret: "nil".into(),
            arity: 1,
        }];
        let out = generate_gleam(&funcs);
        assert!(out.contains("Dict(String, Int)"));
    }
}