use syn::{parse_file, FnArg, ItemFn, Pat, ReturnType};

#[derive(Debug)]
pub struct NifFunc {
    pub name: String,
    pub args: Vec<(String, String)>,
    pub ret: String,
    pub arity: usize,
}

pub fn parse_nif_functions(source: &str) -> Vec<NifFunc> {
    let file = parse_file(source).expect("failed to parse lib.rs");

    let mut functions = Vec::new();
    for item in file.items {
        if let syn::Item::Fn(func) = item {
            if has_gleam_nif(&func.attrs) {
                if let Some(f) = parse_nif_function(func) {
                    functions.push(f);
                }
            }
        }
    }
    functions
}

fn has_gleam_nif(attrs: &[syn::Attribute]) -> bool {
    attrs.iter().any(|a| a.path().is_ident("gleam_nif"))
}

fn parse_nif_function(func: ItemFn) -> Option<NifFunc> {
    let name = func.sig.ident.to_string();
    let mut args = Vec::new();

    for (idx, arg) in func.sig.inputs.iter().enumerate() {
        if let FnArg::Typed(pat_type) = arg {
            let ty = type_to_string(&pat_type.ty);
            
            if idx == 0 && normalize(&ty).contains("Env") {
                continue;
            }

            let name = match pat_type.pat.as_ref() {
                Pat::Ident(ident) => ident.ident.to_string(),
                _ => format!("arg{}", idx),
            };
            args.push((name, ty));
        }
    }

    let ret = match &func.sig.output {
        ReturnType::Default => "nil".to_string(),
        ReturnType::Type(_, ty) => type_to_string(ty),
    };

    let arity = args.len();
    Some(NifFunc { name, args, ret, arity })
}

fn type_to_string(ty: &syn::Type) -> String {
    use quote::ToTokens;
    ty.to_token_stream().to_string()
}

fn normalize(s: &str) -> String {
    s.split_whitespace().collect()
}

pub fn generate_erl(funcs: &[NifFunc]) -> String {
    let exports: Vec<_> = funcs.iter().map(|f| format!("{}/{}", f.name, f.arity)).collect();
    let stubs: Vec<_> = funcs.iter().map(|f| {
        let args: Vec<_> = (0..f.arity).map(|i| format!("_{}", (b'A' + i as u8) as char)).collect();
        format!("{}({}) -> exit(nif_library_not_loaded).", f.name, args.join(", "))
    }).collect();

    format!(
        r#"-module(gleamler_nif_ffi).
-export([{}]).

-on_load(init/0).

init() ->
    PrivDir = case code:which(?MODULE) of
        non_existing ->
            {{ok, Cwd}} = file:get_cwd(),
            filename:join(Cwd, "priv");
        BeamPath ->
            filename:join([filename:dirname(BeamPath), "..", "priv"])
    end,

    LibName = "gleamler",
    Path = filename:join(PrivDir, LibName),

    case erlang:load_nif(Path, 0) of
        ok -> ok;
        Error -> 
            io:format("[Gleamler NIF] Load error: ~p~n", [Error]),
            Error
    end.

{}
"#,
        exports.join(", "),
        stubs.join("\n")
    )
}

pub fn generate_gleam(funcs: &[NifFunc]) -> String {
    let mut out = String::from(
        "// AUTOGENERATED by gleamler_codegen\n\
        // Do not edit\n\n",
    );

    for f in funcs {
        let gleam_name = format!("rust_{}", f.name);
        let args: Vec<_> = f.args.iter().map(|(n, t)| {
            format!("{}: {}", clean_name(n), rust_to_gleam(t))
        }).collect();
        let ret = rust_to_gleam(&f.ret);

        out.push_str(&format!(
            "@external(erlang, \"gleamler_nif_ffi\", \"{}\")\n\
            pub fn {}({}) -> {}\n\n",
            f.name, gleam_name, args.join(", "), ret
        ));
    }
    out
}

fn clean_name(n: &str) -> String {
    n.trim_start_matches('_').to_string()
}

fn rust_to_gleam(rust: &str) -> String {
    let t = normalize(rust);

    if t.starts_with('&') {
        let inner = t[1..].trim();
        if inner == "str" { return "String".into(); }
        return rust_to_gleam(inner);
    }

    match t.as_str() {
        "i8"|"i16"|"i32"|"i64"|"isize"|"u8"|"u16"|"u32"|"u64"|"usize" => "Int".into(),
        "f32"|"f64" => "Float".into(),
        "bool" => "Bool".into(),
        "String" => "String".into(),
        "Atom" => "Atom".into(),
        "Binary"|"OwnedBinary"|"NewBinary" => "BitArray".into(),
        "()" => "Nil".into(),
        _ => {
            if t.starts_with("Vec<") && t.ends_with(">") {
                let inner = &t[4..t.len()-1];
                format!("List({})", rust_to_gleam(inner))
            } else if t.starts_with("Option<") && t.ends_with(">") {
                let inner = &t[7..t.len()-1];
                format!("Option({})", rust_to_gleam(inner))
            } else if t.starts_with("Result<") && t.ends_with(">") {
                let inner = &t[7..t.len()-1];
                let parts = split_args(inner);
                if parts.len() == 2 {
                    format!("Result({}, {})", rust_to_gleam(&parts[0]), rust_to_gleam(&parts[1]))
                } else {
                    "Result(a, b)".into()
                }
            } else if t.starts_with("HashMap<") && t.ends_with(">") {
                let inner = &t[8..t.len()-1];
                let parts = split_args(inner);
                if parts.len() == 2 {
                    format!("Dict({}, {})", rust_to_gleam(&parts[0]), rust_to_gleam(&parts[1]))
                } else {
                    "Dict(k, v)".into()
                }
            } else if t.starts_with("ResourceArc<") && t.ends_with(">") {
                t[12..t.len()-1].to_string()
            } else if t.starts_with('(') && t.ends_with(')') {
                let inner = &t[1..t.len()-1];
                let parts: Vec<_> = inner.split(',').map(|s| rust_to_gleam(s.trim())).collect();
                format!("#({})", parts.join(", "))
            } else {
                t
            }
        }
    }
}

fn split_args(s: &str) -> Vec<String> {
    let mut depth = 0i32;
    let mut cur = String::new();
    let mut res = Vec::new();
    for c in s.chars() {
        match c {
            '<' | '(' => { depth += 1; cur.push(c); }
            '>' | ')' => { depth -= 1; cur.push(c); }
            ',' if depth == 0 => { res.push(cur.trim().to_string()); cur.clear(); }
            _ => cur.push(c),
        }
    }
    if !cur.is_empty() { res.push(cur.trim().to_string()); }
    res
}