[package]
name = "gleamler_macros"
version = "0.1.2"
edition = "2024"
authors = ["Chlon (@chlonishe)"]
license = "MIT OR Apache-2.0"
description = "Procedural macros for the Gleamler NIF framework"
repository = "https://github.com/chlonishe/gleamler"

[lib]
proc-macro = true

[dependencies]
syn = { version = "3.0", features = ["full", "extra-traits"] }
quote = "1.0"
heck = "0.5"
proc-macro2 = "1.0"
