// AUTOGENERATED by gleamler_codegen
// Do not edit

import gleam/dynamic
import gleam/dynamic/decode
import gleam/erlang/process

@external(erlang, "gleamler_nif_ffi", "identity")
@internal
pub fn coerce(a: a) -> b

@external(erlang, "gleamler_nif_ffi", "atom_or_string_to_string")
@internal
pub fn atom_or_string_to_string(term: dynamic.Dynamic) -> Result(String, Nil)

@internal
pub fn check_tag(
  tag_dyn: dynamic.Dynamic,
  expected: String,
  next: fn(Nil) -> decode.Decoder(a),
) -> decode.Decoder(a) {
  case atom_or_string_to_string(tag_dyn) {
    Ok(tag) if tag == expected -> next(Nil)
    _ -> decode.failure(coerce(Nil), expected)
  }
}

/// Messages sent from the background worker to the Gleam actor
pub type WorkerMsg {
  Progress(Int)
  Done(String)
}

pub fn worker_msg_decoder() -> decode.Decoder(WorkerMsg) {
  decode.one_of(
    {
      use tag_dyn <- decode.field(0, decode.dynamic)
      use _ <- check_tag(tag_dyn, "progress")
      use field_0 <- decode.field(1, decode.int)
      decode.success(Progress(field_0))
    },
    [
      {
        use tag_dyn <- decode.field(0, decode.dynamic)
        use _ <- check_tag(tag_dyn, "done")
        use field_0 <- decode.field(1, decode.string)
        decode.success(Done(field_0))
      },
    ],
  )
}

/// Starts a long-running task in an OS background thread.
/// Returns immediately to Gleam without blocking the BEAM scheduler.
/// Automatically cancels the background thread if the calling Gleam actor dies.
@external(erlang, "gleamler_nif_ffi", "start_work")
pub fn rust_start_work(subject: process.Subject(WorkerMsg), steps: Int) -> Bool
