// AUTOGENERATED by gleamler_codegen
// Do not edit


/// Messages sent from the background worker to the Gleam actor
pub type WorkerMsg {
  Progress(Int)
  Done(String)
}

/// Starts a long-running task in an OS background thread.
/// Returns immediately to Gleam without blocking the BEAM scheduler
@external(erlang, "gleamler_nif_ffi", "start_work")
pub fn rust_start_work(subject: process.Subject(WorkerMsg), steps: Int) -> Bool
