// AUTOGENERATED by gleamler_codegen
// Do not edit

/// Recursive Fibonacci. Exponential time — a classic `dirty_cpu` candidate.
@external(erlang, "gleamler_nif_ffi", "fib")
pub fn rust_fib(n: Int) -> Int

/// Sleeps the calling dirty-IO thread. Negative input is clamped to zero
/// to avoid a panic in `Duration::from_millis`.
@external(erlang, "gleamler_nif_ffi", "sleep_ms")
pub fn rust_sleep_ms(ms: Int) -> Int
