// AUTOGENERATED by gleamler_codegen
// Do not edit

import gleam/dict
import gleam/option

pub opaque type Resource {
  Resource
}

@internal
pub fn resource_dummy() -> Resource {
  Resource
}

pub type GleamlerError {
  BadArg
  Panic(String)
  Custom(String)
}

/// A user record synchronized between Rust and Gleam
pub type User {
  User(id: Int, name: String, is_active: Bool)
}

/// Status enum synchronized between Rust and Gleam
pub type UserStatus {
  Pending
  Active
  Banned
}

@external(erlang, "gleamler_nif_ffi", "make_user")
pub fn rust_make_user(id: Int, name: String) -> User

@external(erlang, "gleamler_nif_ffi", "user_get_name")
pub fn rust_user_get_name(user: User) -> String

@external(erlang, "gleamler_nif_ffi", "is_user_banned")
pub fn rust_is_user_banned(status: UserStatus) -> Bool

@external(erlang, "gleamler_nif_ffi", "counter_new")
pub fn rust_counter_new(target: Int) -> Resource

@external(erlang, "gleamler_nif_ffi", "counter_read")
pub fn rust_counter_read(counter: Resource) -> Int

@external(erlang, "gleamler_nif_ffi", "cooperative_count")
pub fn rust_cooperative_count(counter: Resource) -> Int

@external(erlang, "gleamler_nif_ffi", "add")
pub fn rust_add(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "sub")
pub fn rust_sub(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "greet")
pub fn rust_greet(name: String) -> String

@external(erlang, "gleamler_nif_ffi", "double_list")
pub fn rust_double_list(items: List(Int)) -> List(Int)

@external(erlang, "gleamler_nif_ffi", "is_positive")
pub fn rust_is_positive(n: Int) -> Bool

@external(erlang, "gleamler_nif_ffi", "divide")
pub fn rust_divide(a: Float, b: Float) -> Float

@external(erlang, "gleamler_nif_ffi", "make_pair")
pub fn rust_make_pair(a: Int, b: String) -> #(Int, String)

@external(erlang, "gleamler_nif_ffi", "factorial")
pub fn rust_factorial(n: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "fib")
pub fn rust_fib(n: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "echo_i128")
pub fn rust_echo_i128(n: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "echo_u128")
pub fn rust_echo_u128(n: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "mul")
pub fn rust_mul(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "net_ip_roundtrip")
pub fn rust_net_ip_roundtrip(ip: String) -> String

@external(erlang, "gleamler_nif_ffi", "net_socket_roundtrip")
pub fn rust_net_socket_roundtrip(addr: #(String, Int)) -> #(String, Int)

@external(erlang, "gleamler_nif_ffi", "net_socket_v4_roundtrip")
pub fn rust_net_socket_v4_roundtrip(addr: #(String, Int)) -> #(String, Int)

@external(erlang, "gleamler_nif_ffi", "net_socket_v6_roundtrip")
pub fn rust_net_socket_v6_roundtrip(addr: #(String, Int)) -> #(String, Int)

@external(erlang, "gleamler_nif_ffi", "collections_hashset_roundtrip")
pub fn rust_collections_hashset_roundtrip(set: List(Int)) -> List(Int)

@external(erlang, "gleamler_nif_ffi", "collections_btreeset_roundtrip")
pub fn rust_collections_btreeset_roundtrip(set: List(String)) -> List(String)

@external(erlang, "gleamler_nif_ffi", "collections_vecdeque_roundtrip")
pub fn rust_collections_vecdeque_roundtrip(dq: List(Int)) -> List(Int)

@external(erlang, "gleamler_nif_ffi", "collections_linkedlist_roundtrip")
pub fn rust_collections_linkedlist_roundtrip(ll: List(Bool)) -> List(Bool)

@external(erlang, "gleamler_nif_ffi", "collections_btreemap_roundtrip")
pub fn rust_collections_btreemap_roundtrip(
  map: dict.Dict(String, Int),
) -> dict.Dict(String, Int)

@external(erlang, "gleamler_nif_ffi", "time_system_time_roundtrip")
pub fn rust_time_system_time_roundtrip(t: #(Int, Int, Int)) -> #(Int, Int, Int)

@external(erlang, "gleamler_nif_ffi", "safe_div")
pub fn rust_safe_div(a: Float, b: Float) -> Result(Float, GleamlerError)

@external(erlang, "gleamler_nif_ffi", "safe_panic_recovery")
pub fn rust_safe_panic_recovery(trigger: Bool) -> Result(Int, GleamlerError)

@external(erlang, "gleamler_nif_ffi", "stress_i128_min")
pub fn rust_stress_i128_min() -> Int

@external(erlang, "gleamler_nif_ffi", "stress_i128_max")
pub fn rust_stress_i128_max() -> Int

@external(erlang, "gleamler_nif_ffi", "stress_u128_max")
pub fn rust_stress_u128_max() -> Int

@external(erlang, "gleamler_nif_ffi", "stress_i64_max")
pub fn rust_stress_i64_max() -> Int

@external(erlang, "gleamler_nif_ffi", "stress_u64_max")
pub fn rust_stress_u64_max() -> Int

@external(erlang, "gleamler_nif_ffi", "stress_add_wrap")
pub fn rust_stress_add_wrap(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_mul_wrap")
pub fn rust_stress_mul_wrap(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_repeat_string")
pub fn rust_stress_repeat_string(s: String, n: Int) -> String

@external(erlang, "gleamler_nif_ffi", "stress_string_len")
pub fn rust_stress_string_len(s: String) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_sum_list")
pub fn rust_stress_sum_list(items: List(Int)) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_reverse_list")
pub fn rust_stress_reverse_list(items: List(Int)) -> List(Int)

@external(erlang, "gleamler_nif_ffi", "stress_panic")
pub fn rust_stress_panic(msg: String) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_dirty_cpu")
pub fn rust_stress_dirty_cpu(n: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_dirty_io")
pub fn rust_stress_dirty_io(ms: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "stress_float_div")
pub fn rust_stress_float_div(a: Float, b: Float) -> Float

@external(erlang, "gleamler_nif_ffi", "stress_tuple_swap")
pub fn rust_stress_tuple_swap(a: Int, b: String) -> #(String, Int)

@external(erlang, "gleamler_nif_ffi", "stress_maybe_div")
pub fn rust_stress_maybe_div(a: Float, b: Float) -> option.Option(Float)

@external(erlang, "gleamler_nif_ffi", "stress_safe_sqrt")
pub fn rust_stress_safe_sqrt(n: Float) -> Result(Float, String)

@external(erlang, "gleamler_nif_ffi", "stress_now_ms")
pub fn rust_stress_now_ms() -> Int

@external(erlang, "gleamler_nif_ffi", "stress_float_is_special")
pub fn rust_stress_float_is_special(n: Float) -> String

@external(erlang, "gleamler_nif_ffi", "stress_resource_roundtrip")
pub fn rust_stress_resource_roundtrip() -> Resource

@external(erlang, "gleamler_nif_ffi", "stress_resource_intentional_leak")
pub fn rust_stress_resource_intentional_leak() -> Nil
