// AUTOGENERATED by gleamler_codegen
// Do not edit

@external(erlang, "gleamler_nif_ffi", "add")
pub fn rust_add(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "sub")
pub fn rust_sub(a: Int, b: Int) -> Int

@external(erlang, "gleamler_nif_ffi", "greet")
pub fn rust_greet(name: String) -> String

@external(erlang, "gleamler_nif_ffi", "double_list")
pub fn rust_double_list(items: List(Int)) -> List(Int)

@external(erlang, "gleamler_nif_ffi", "is_positive")
pub fn rust_is_positive(n: Int) -> Bool

@external(erlang, "gleamler_nif_ffi", "divide")
pub fn rust_divide(a: Float, b: Float) -> Float

@external(erlang, "gleamler_nif_ffi", "make_pair")
pub fn rust_make_pair(a: Int, b: String) -> #(Int, String)

@external(erlang, "gleamler_nif_ffi", "factorial")
pub fn rust_factorial(n: Int) -> Int

